name: Tests

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - '*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm install and test
      run: |
        npm cit
      env:
        CI: true

    - name: Coverage report
      uses: codecov/codecov-action@v1
